### ISSUE TITLE
Questions to Antione / Gaspard

### ISSUE THREAD

**Issue by tsufz** [tsufz/mar23cds_accidents#2]
# Session on 16 June
- [x] Do we need to use all data on the [governmental platform](https://www.data.gouv.fr/en/datasets/bases-de-donnees-annuelles-des-accidents-corporels-de-la-circulation-routiere-annees-de-2005-a-2019) or is the [Kaggle](https://www.kaggle.com/ahmedlahlou/accidents-in-france-from-2005-to-2016 ) data sufficient?

**Comment by tiagoru** [comment]
answer from Antoine: The data from the french government

**Comment by tsufz** [comment]
Okay, I will download, merge the data and update the data folder
